name: Deploy to DEV Backend Remote Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Node.js version 20
          cache: "npm" # Enable caching for npm

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Npm Run Build
        run: |
          npm run build
        working-directory: backend

      - name: Setup SSH Backend
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo "$AWS_SSH_HOST" > ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
        env:
          AWS_SSH_HOST: ${{ secrets.EC2_IP }}
          AWS_SSH_USER: ubuntu

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_DEV_BACKEND }}" > .env
          cat .env > ./dist/.env  # Copy .env to the build directory
        working-directory: backend

      - name: Check env
        run: |
          ls -alh

          ls -alh ./dist
        working-directory: backend

      - name: Deploy to Remote Server
        run: |
          BACKEND_URL="https://nqjz8oephd.execute-api.us-east-1.amazonaws.com/dev/"
          _remote="${{secrets.EC2_IP}}"
          _user="ubuntu"
          _remote_directory_name="refocus-backend"

          rsync -rtu --delete --progress --compress "./dist/" --exclude="node_modules" --exclude="tmp" $_user@$_remote:/home/ubuntu/$_remote_directory_name

          ssh -T "$_user"@"$_remote" "bash -s $_remote_directory_name" <<'EOL'
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
              export HOME="/home/ubuntu/"
              now="$(date)"
              name="$HOSTNAME"
              up="$(uptime)"
              echo "Server name is $name"
              echo "Server date and time is $now"
              echo "Server uptime: $up"
              echo "remote_directory_name : $1"
              _remote_directory_name=$1
              _pm2_server_ref=$1

              echo "current directory : $pwd"

              cd /home/ubuntu/$_remote_directory_name

              echo "current directory : $pwd"
              nvm use v22
              echo "installing node module : $pwd"
              npm install

              npm run migration:run


              pm2 stop $_pm2_server_ref --silent
              pm2 delete $_pm2_server_ref --silent
              pm2 start main.js --name $_pm2_server_ref --time
              pm2 save

              echo "Deployment Ended Local system name: $HOSTNAME"
              echo "Deployment Ended Local date and time: $(date)"
              echo "Bye"

              echo "$BACKEND_URL"
          EOL
        working-directory: backend
