name: Deploy to Frontend s3 and cloudfront

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checaukout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Node.js version 20
          cache: "npm" # Enable caching for npm

      - name: Install dependencies
        run: npm install

      - name: Npm Run Build
        run: |
          npm run build
