name: Deploy to Frontend Remote Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-24.04

    env:
      NEXT_PUBLIC_API_BASE_URL: https://nqjz8oephd.execute-api.us-east-1.amazonaws.com/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo snap install aws-cli --classic

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" # Node.js version 20
          cache: "npm" # Enable caching for npm
          cache-dependency-path: "backend/package-lock.json"

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Npm Run Build
        run: |
          npm run build
        working-directory: frontend

      - name: Sync build files to S3
        run: |
          aws s3 sync out/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --acl public-read
        working-directory: frontend

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Frontend URL
        run: |
          FRONTEND_URL="https://d2sjftcgakx66y.cloudfront.net"
          echo "$FRONTEND_URL"
